# Generated by Django 2.2.6 on 2019-11-07 20:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donaypage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donaypage',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
