# Generated by Django 2.2.6 on 2019-11-09 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donaypage', '0002_auto_20191107_2046'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonayReceivedTransactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=30)),
                ('amount', models.BigIntegerField()),
                ('sender_name', models.CharField(max_length=50)),
                ('donaypage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donaypage.DonayPage')),
            ],
        ),
    ]
