# Generated by Django 2.2.6 on 2019-11-09 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donaypage', '0003_donayreceivedtransactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donayreceivedtransactions',
            name='amount',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='donayreceivedtransactions',
            name='reference',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='donayreceivedtransactions',
            name='sender_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
